name: Enforce PR Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR branch requirements
        run: |
          BASE_REF="${{ github.base_ref }}"
          HEAD_REF="${{ github.head_ref }}"

          if [[ "${BASE_REF}" == "prod" && "${HEAD_REF}" != "staging" ]]; then
            echo "PRs to 'prod' must be from 'staging'."
            exit 1
          elif [[ "${BASE_REF}" == "staging" && "${HEAD_REF}" != "master" ]]; then
            echo "PRs to 'staging' must be from 'master'."
            exit 1
          fi
